version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2
    steps:
      - checkout
      - run: echo "hello world"
      - run: go run main.go

workflows:
  version: 2
  build:
    jobs:
      - build
